SELECT MIN(PRACOWNICY.ZAROBEK) AS "MinimalnyZarobek",PRACOWNICY.STANOWISKO FROM PRACOWNICY
INNER JOIN DZIAL ON PRACOWNICY.NR_DZIALU=DZIAL.NR_DZIALU
WHERE DZIAL.LOKALIZACJA='POZNAN' GROUP BY PRACOWNICY.STANOWISKO ORDER BY MIN (PRACOWNICY.ZAROBEK) ASC;