SELECT FILM.T_FILMU,KINO.N_KINA,MIASTO.MIASTO,
KIEROWNIK.N_KIEROWNIKA FROM SEANS INNER JOIN FILM ON SEANS.FILM_N_FILMU=FILM.N_FILMU
INNER JOIN KINO ON SEANS SEANS.KINO_K_KINA=KINO.K_KINA INNER JOIN MIASTO ON KINO.MIASTO_MIASTO=MIASTO.MIASTO
INNER JOIN KIEROWNIK ON KINO.KIEROWNIK_NR_KIEROWNIKA=KIEROWNIK.NR_KIEROWNIKA
WHERE SEANS.L_SEANSOW IN ((SELECT MIN(L_SEANSOW) FROM SEANS GROUP BY FILM_N_FILMU));