INSERT ALL
INTO KSIAZKA VALUES (1,'Avatar','James Cameron',30,1)
INTO KSIAZKA VALUES (2,'Kot w Butach','Tatsuhiko shibusawa',20,1)
INTO KSIAZKA VALUES (3,'Sherwood','Tomasz Pacyński',15,2)
INTO KSIAZKA VALUES (4,'Przypadki Robinsona Kruzoe','Christophe Gaultier',10,3)
INTO KSIAZKA VALUES (5,'Przypadki Robinsona Kruzoe','Daniel Defoe',10,2)
INTO KSIAZKA VALUES (6,'Anastasia','Władimir Megre',5,4)
INTO KSIAZKA VALUES (7,'Władca Pierścieni','J.R.R Tolkien',40,4)
INTO KSIAZKA VALUES (8,'Władca Pierścieni','J.R.R Tolkien',20,2)
INTO KSIAZKA VALUES (9,'Władca Pierścieni','J.R.R Tolkien',10,1)
INTO KSIAZKA VALUES (10,'Amnezja','Lisa Unger',15,3)
SELECT 1 FROM DUAL

INSERT ALL
INTO BIBLIOTEKA VALUES (1,'Omnibus','Jana Dekerta 2,41-200 Sosnowiec','10:00-17:00')
INTO BIBLIOTEKA VALUES (2,'Bookland','Bytomska 7,44-102 Gliwice','09:00-17:00')
INTO BIBLIOTEKA VALUES (3,'Tak Czytam','3 Maja 13,40-096 Katowice','09:00-19:00')
INTO BIBLIOTEKA VALUES (4,'Lubimy Czytać','Bulwarowa 7A,31-751 Kraków','10:00-18:00')
SELECT 1 FROM DUAL

INSERT ALL
INTO PRACOWNIK VALUES (1,'Paul','Tereman','Sprzedawca',1)
INTO PRACOWNIK VALUES (2,'Herman','Bytomski','Dostawca',1)
INTO PRACOWNIK VALUES (3,'Zbiginiew','Weron','Zarzadca',1)
INTO PRACOWNIK VALUES (4,'Tojo','Zaraza','Sprzedawca',2)
INTO PRACOWNIK VALUES (5,'Mariko','Caraman','Dostawca',3)
INTO PRACOWNIK VALUES (6,'Benedykt','Harbringer','Magazynier',3)
INTO PRACOWNIK VALUES (7,'Jon','Weskos','Magazynier',2)
INTO PRACOWNIK VALUES (8,'Wanda','Tereman','Sprzedawczyni',2)
INTO PRACOWNIK VALUES (9,'Jolanta','Wicyk','Sprzedawczyni',4)
INTO PRACOWNIK VALUES (10,'Adam','Mickiewicz','Kustosz',4)
INTO PRACOWNIK VALUES (11,'Irena','Dendryl','Magazynier',3)
INTO PRACOWNIK VALUES (12,'Eve','Tesmaker','Zarzadca',4)
SELECT 1 FROM DUAL

INSERT ALL
INTO KLIENT VALUES (1,'Teresa','Racinger','Dworcowa 26, 44-100 Gliwice')
INTO KLIENT VALUES (2,'Froyd','Bromski','Jaszczurcza Góra 28, 11-700 Mrągowo')
INTO KLIENT VALUES (3,'Władysław','Kaszubski','Cicha Woda 3, 34-500 Zakopane')
INTO KLIENT VALUES (4,'Cleo','Donatan','Lubieszyn 11a, 72-002 Dołuje')
INTO KLIENT VALUES (5,'Weronika','Kaszubska','Jana Heweliusza 24,80-861 Gdańsk')
INTO KLIENT VALUES (6,'Henryk','Wielki','Ul. Gnieźnieńska 11,Cielimowo')
INTO KLIENT VALUES (7,'Joanna','Zinger','Klimczoka 7, 40-867 Katowice')
INTO KLIENT VALUES (8,'Marcus','Newborn','Przy Rondzie 2,31-547 Kraków')
SELECT 1 FROM DUAL

INSERT ALL
INTO ZAMOWIENIE VALUES (1,1,'2021-03-31','NIE','Mikołaja Kopernika 6, 40-064 Katowice')
INTO ZAMOWIENIE VALUES (4,2,'2021-03-20','TAK','Eljasza Radzikowskiego 142, 31-342 Kraków')
INTO ZAMOWIENIE VALUES (5,3,'2020-02-15','TAK','Klimczoka 7, 40-857 Katowice')
INTO ZAMOWIENIE VALUES (7,4,'2020-08-16','NIE','Przy Rondzie 2, 31-547 Kraków')
INTO ZAMOWIENIE VALUES (8,5,'2020-12-23','TAK','Modrzejowska 3, 41-200 Sosnowiec')
SELECT 1 FROM DUAL

INSERT ALL
INTO WYPOZYCZONA VALUES (1,1,20,'2021/03/10','2023/04/03')
INTO WYPOZYCZONA VALUES (10,2,7,'2020/02/06','2022/03/15')
INTO WYPOZYCZONA VALUES (9,3,10,'2021/04/15','2022/09/13')
INTO WYPOZYCZONA VALUES (4,4,10,'2020/12/12','2022/11/15')
INTO WYPOZYCZONA VALUES (2,5,2,'2021/05/26','2021/09/18')
SELECT 1 FROM DUAL

SELECT NAZWA FROM KSIAZKA WHERE NAZWA LIKE 'A%';
SELECT COUNT(*) AS "ZAMÓWIENIA WYKONANE" FROM ZAMOWIENIE WHERE ZREALIZOWANE='TAK';
SELECT KLIENT.*,ZAMOWIENIE.* FROM KLIENT
INNER JOIN ZAMOWIENIE ON KLIENT.ID_KLIENTA=ZAMOWIENIE.KLIENT_ID_KLIENTA
ORDER BY ZAMOWIENIE.ID_ZAMOWIENIA ASC;
UPDATE KSIAZKA SET ILOSC=50 WHERE NAZWA='Amnezja';
SELECT WYPOZYCZONA.* FROM WYPOZYCZONA WHERE
	DO_KIEDY LIKE '22%'
OR
	DO_KIEDY LIKE '23%';
SELECT PRACOWNIK.ID_PRACOWNIKA,PRACOWNIK.IMIE,PRACOWNIK.NAZIWSKO,PRACOWNIK.STANOWISKO,
BIBLIOTEKA.NAZWA.BIBLIOTEKI,BIBLIOTEKA.ADRES_BIBLIOTEKI,BIBLIOTEKA.GODZINY_OTWARCIA FROM PRACOWNIK
INNER JOIN BIBLIOTEKA ON PRACOWNIK.BIBLIOTEKA_ID_BIBLIOTEKI=BIBLIOTEKA.ID_BIBLIOTEKI WHERE ADRES_BIBLIOTEKI NOT LIKE '%Katowice%';
SELECT ZAMOWIENIE.*,KLIENT.NAZIWSKO FROM ZAMOWIENIE
INNER JOIN KLIENT ON ZAMOWIENIE.KLIENT_ID_KLIENTA=KLIENT.ID_KLIENTA WHERE DATA_ZLOZENIA LIKE '21%';
SELECT (KSIAZKA.ILOSC-WYPOZYCZONA.ILOSC) AS "NA STANIE" FROM KSIAZKA,WYPOZYCZONA
WHERE KSIAZKA.ID_KSIAZKI=WYPOZYCZONA.KSIAZKA_ID_KSIAZKI AND KSIAZKA.NAZWA='Władca Pierścieni';
SELECT BIBLIOTEKA.NAZWA_BIBLIOTEKI,BIBLIOTEKA.ADRES_BIBLIOTEKI,BIBLIOTEKA.GODZINY_OTWARCIA
FROM BIBLIOTEKA WHERE BIBLIOTEKA.ID_BIBLIOTEKI IN (SELECT KSIAZKA.BIBLIOTEKA_ID_BIBLIOTEKI FROM KSIAZKA WHERE KSIAZKA.NAZWA='Władca Pierścieni');